// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGP-akInABRosfs0-L9SQH7Nx2YBDb8Eo',
    appId: '1:705873184040:android:eff50a95f83dc30a06fc1d',
    messagingSenderId: '705873184040',
    projectId: 'mzadcom-2-0',
    databaseURL: 'https://mzadcom-2-0.firebaseio.com',
    storageBucket: 'mzadcom-2-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyxkNr6WgL6KyNloOG3qCFfsR_65nl5Y8',
    appId: '1:705873184040:ios:e92d56e5bd31b76606fc1d',
    messagingSenderId: '705873184040',
    projectId: 'mzadcom-2-0',
    databaseURL: 'https://mzadcom-2-0.firebaseio.com',
    storageBucket: 'mzadcom-2-0.firebasestorage.app',
    androidClientId: '705873184040-kr2r6n8trjvkoo7hcr4hd5j2k4qo4kk1.apps.googleusercontent.com',
    iosClientId: '705873184040-92ukvq4vclciqbn43ltjnianghc687ri.apps.googleusercontent.com',
    iosBundleId: 'com.example.mzadcom',
  );
}
